// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package litedb

type GasAuthApiKey struct {
	ID        string
	Subject   string
	Name      string
	KeyHash   string
	KeyPrefix string
	Scopes    string
	Metadata  string
	LastUsed  *string
	ExpiresAt *string
	CreatedAt string
	DeletedAt *string
}
