// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package litedb

import (
	"context"
)

const getKeyByHash = `-- name: GetKeyByHash :one
SELECT id, subject, name, key_hash, key_prefix, scopes, metadata, last_used, expires_at, created_at, deleted_at
FROM __gas_auth_api_keys
WHERE key_hash = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetKeyByHash(ctx context.Context, keyHash string) (*GasAuthApiKey, error) {
	row := q.db.QueryRowContext(ctx, getKeyByHash, keyHash)
	var i GasAuthApiKey
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.Metadata,
		&i.LastUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const hardDeleteKeyByID = `-- name: HardDeleteKeyByID :exec
DELETE
FROM __gas_auth_api_keys
WHERE id = ?
`

func (q *Queries) HardDeleteKeyByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteKeyByID, id)
	return err
}

const hardDeleteKeysBySubject = `-- name: HardDeleteKeysBySubject :exec
DELETE
FROM __gas_auth_api_keys
WHERE subject = ?
`

func (q *Queries) HardDeleteKeysBySubject(ctx context.Context, subject string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteKeysBySubject, subject)
	return err
}

const insertKey = `-- name: InsertKey :exec
INSERT INTO __gas_auth_api_keys (id, subject, name, key_hash, key_prefix, scopes, metadata, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertKeyParams struct {
	ID        string
	Subject   string
	Name      string
	KeyHash   string
	KeyPrefix string
	Scopes    string
	Metadata  string
	ExpiresAt *string
	CreatedAt string
}

func (q *Queries) InsertKey(ctx context.Context, arg *InsertKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertKey,
		arg.ID,
		arg.Subject,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scopes,
		arg.Metadata,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const listAllKeysBySubject = `-- name: ListAllKeysBySubject :many
SELECT id, subject, name, key_hash, key_prefix, scopes, metadata, last_used, expires_at, created_at, deleted_at
FROM __gas_auth_api_keys
WHERE subject = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAllKeysBySubject(ctx context.Context, subject string) ([]*GasAuthApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAllKeysBySubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GasAuthApiKey
	for rows.Next() {
		var i GasAuthApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Scopes,
			&i.Metadata,
			&i.LastUsed,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeysBySubject = `-- name: ListKeysBySubject :many
SELECT id, subject, name, key_hash, key_prefix, scopes, metadata, last_used, expires_at, created_at, deleted_at
FROM __gas_auth_api_keys
WHERE subject = ?
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListKeysBySubject(ctx context.Context, subject string) ([]*GasAuthApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listKeysBySubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GasAuthApiKey
	for rows.Next() {
		var i GasAuthApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Scopes,
			&i.Metadata,
			&i.LastUsed,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteKeyByID = `-- name: SoftDeleteKeyByID :exec
UPDATE __gas_auth_api_keys
SET deleted_at = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type SoftDeleteKeyByIDParams struct {
	DeletedAt *string
	ID        string
}

func (q *Queries) SoftDeleteKeyByID(ctx context.Context, arg *SoftDeleteKeyByIDParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteKeyByID, arg.DeletedAt, arg.ID)
	return err
}

const softDeleteKeysBySubject = `-- name: SoftDeleteKeysBySubject :exec
UPDATE __gas_auth_api_keys
SET deleted_at = ?
WHERE subject = ?
  AND deleted_at IS NULL
`

type SoftDeleteKeysBySubjectParams struct {
	DeletedAt *string
	Subject   string
}

func (q *Queries) SoftDeleteKeysBySubject(ctx context.Context, arg *SoftDeleteKeysBySubjectParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteKeysBySubject, arg.DeletedAt, arg.Subject)
	return err
}

const updateLastUsed = `-- name: UpdateLastUsed :exec
UPDATE __gas_auth_api_keys
SET last_used = ?
WHERE id = ?
`

type UpdateLastUsedParams struct {
	LastUsed *string
	ID       string
}

func (q *Queries) UpdateLastUsed(ctx context.Context, arg *UpdateLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateLastUsed, arg.LastUsed, arg.ID)
	return err
}
