// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package litedb

type GasAuthSession struct {
	ID         string
	Subject    string
	Metadata   string
	IpAddress  string
	UserAgent  string
	CreatedAt  string
	ExpiresAt  string
	LastActive string
}
