// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package litedb

import (
	"context"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE
FROM __gas_auth_sessions
WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE
FROM __gas_auth_sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsBySubject = `-- name: DeleteSessionsBySubject :exec
DELETE
FROM __gas_auth_sessions
WHERE subject = ?
`

func (q *Queries) DeleteSessionsBySubject(ctx context.Context, subject string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsBySubject, subject)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE __gas_auth_sessions
SET expires_at  = ?,
    last_active = ?
WHERE id = ?
`

type ExtendSessionParams struct {
	ExpiresAt  string
	LastActive string
	ID         string
}

func (q *Queries) ExtendSession(ctx context.Context, arg *ExtendSessionParams) error {
	_, err := q.db.ExecContext(ctx, extendSession, arg.ExpiresAt, arg.LastActive, arg.ID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, subject, metadata, ip_address, user_agent, created_at, expires_at, last_active
FROM __gas_auth_sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (*GasAuthSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i GasAuthSession
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActive,
	)
	return &i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO __gas_auth_sessions (id, subject, metadata, ip_address, user_agent, created_at, expires_at, last_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID         string
	Subject    string
	Metadata   string
	IpAddress  string
	UserAgent  string
	CreatedAt  string
	ExpiresAt  string
	LastActive string
}

func (q *Queries) InsertSession(ctx context.Context, arg *InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.Subject,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastActive,
	)
	return err
}
