// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pgdb

import (
	"context"
	"time"
)

const consumeTokenByHash = `-- name: ConsumeTokenByHash :one
DELETE
FROM __gas_auth_tokens
WHERE token_hash = $1
RETURNING id, subject, purpose, expires_at
`

type ConsumeTokenByHashRow struct {
	ID        string
	Subject   string
	Purpose   string
	ExpiresAt time.Time
}

func (q *Queries) ConsumeTokenByHash(ctx context.Context, tokenHash string) (*ConsumeTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, consumeTokenByHash, tokenHash)
	var i ConsumeTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Purpose,
		&i.ExpiresAt,
	)
	return &i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :execrows
DELETE
FROM __gas_auth_tokens
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTokenByHash = `-- name: DeleteTokenByHash :execrows
DELETE
FROM __gas_auth_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteTokenByHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTokenByHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTokensBySubjectPurpose = `-- name: DeleteTokensBySubjectPurpose :exec
DELETE
FROM __gas_auth_tokens
WHERE subject = $1
  AND purpose = $2
`

type DeleteTokensBySubjectPurposeParams struct {
	Subject string
	Purpose string
}

func (q *Queries) DeleteTokensBySubjectPurpose(ctx context.Context, arg *DeleteTokensBySubjectPurposeParams) error {
	_, err := q.db.ExecContext(ctx, deleteTokensBySubjectPurpose, arg.Subject, arg.Purpose)
	return err
}

const insertToken = `-- name: InsertToken :exec
INSERT INTO __gas_auth_tokens (id, subject, token_hash, purpose, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTokenParams struct {
	ID        string
	Subject   string
	TokenHash string
	Purpose   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertToken(ctx context.Context, arg *InsertTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertToken,
		arg.ID,
		arg.Subject,
		arg.TokenHash,
		arg.Purpose,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
