// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package litedb

type GasAuthToken struct {
	ID        string
	Subject   string
	TokenHash string
	Purpose   string
	CreatedAt string
	ExpiresAt string
}
