// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"encoding/json"
	"time"
)

type GasAuthSession struct {
	ID         string
	Subject    string
	Metadata   json.RawMessage
	IpAddress  string
	UserAgent  string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastActive time.Time
}
