// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mydb

import (
	"database/sql"
	"encoding/json"
	"time"
)

type GasAuthApiKey struct {
	ID        string
	Subject   string
	Name      string
	KeyHash   string
	KeyPrefix string
	Scopes    string
	Metadata  json.RawMessage
	LastUsed  sql.NullTime
	ExpiresAt sql.NullTime
	CreatedAt time.Time
	DeletedAt sql.NullTime
}
